on:
  push:
    branches:
    - main
  pull_request:
name: ci
jobs:
  install-shared-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.1
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 8
    - run: java -version
    - name: Checkout repositories
      run: |
        bash checkout.sh
    - name: Install Maven projects for the shared dependencies
      run: |
        for D in google-auth-library-java java-core java-shared-dependencies; do
          mvn --batch-mode --no-transfer-progress install --file $D \
            -DskipTests=true -Dclirr.skip=true -Denforcer.skip=true \
            -Dmaven.javadoc.skip=true
        done
    - name: Save the compiled libraries into cache to share subsequent jobs
      uses: actions/cache@v2
      id: mvn-cache
      with:
        path: ~/.m2/repository
        # This cache is only hit by the subsequent job within the same run
        key: ${{ runner.os }}-maven-unified-${{ github.run_id }}
  units:
    needs: install-shared-dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        submodule:
          - google-auth-library-java
          - java-core
          - java-iam-admin
          - java-iamcredentials
          - java-bigquery
    steps:
      - uses: actions/checkout@v2
      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.1
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - run: java -version
      - name: Checkout repositories
        run: |
          bash checkout.sh
      - name: Restore the compiled libraries
        uses: actions/cache@v2
        id: mvn-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-unified-${{ github.run_id }}
      - run: |
          ls -alt
      - run: |
          ls -alt ${{ matrix.submodule }}
      - run: .kokoro/build.sh
        env:
          JOB_TYPE: test
        working-directory: ${{ matrix.submodule }}
